import 'package:today_s_farm/models/product_model.dart';

class DataProducts {
  static final List<Product> products = [
    Product(
      name: '익산 고구마 5kg',
      price: 16000,
      description: '단단하고 달콤한 익산 고구마입니다.',
      imageUrl: 'assets/bokdong_iksan_sweetpotato.png',
      origin: '전북 익산',
      farmer: '조갑수',
      deliveryDate: 1,
      star: 4.5,
      reviewCount: 2376,
    ),
    Product(
      name: '평창 감자 3kg',
      price: 9000,
      description: '신선한 평창 감자입니다.',
      imageUrl: 'assets/bongsik_pyungchang_potato.png',
      origin: '강원 평창',
      farmer: '이봉식',
      deliveryDate: 2,
      star: 4.0,
      reviewCount: 1514,
    ),
    Product(
      name: '청주 사과 2kg',
      price: 12000,
      description: '달콤하고 아삭한 청주 사과입니다.',
      imageUrl: 'assets/chuljin_chungju_apple.png',
      origin: '충북 청주',
      farmer: '최철진',
      deliveryDate: 1,
      star: 4.8,
      reviewCount: 2453,
    ),
    Product(
      name: '서산 딸기 1kg',
      price: 15000,
      description: '신선한 서산 딸기입니다.',
      imageUrl: 'assets/donggu_seosan_strawberrie.png',
      origin: '충남 서산',
      farmer: '한동구',
      deliveryDate: 3,
      star: 4.6,
      reviewCount: 1238,
    ),
    Product(
      name: '강원도 옥수수 5개',
      price: 8000,
      description: '단단하고 달콤한 강원도 옥수수입니다.',
      imageUrl: 'assets/dongwon_gangwon_corn.png',
      origin: '강원 강릉',
      farmer: '박동원',
      deliveryDate: 2,
      star: 4.2,
      reviewCount: 1024,
    ),
    Product(
      name: '고창 수박 1개',
      price: 18000,
      description: '달콤하고 시원한 고창 수박입니다.',
      imageUrl: 'assets/gabsoo_gochang_watermelon.png',
      origin: '전북 고창',
      farmer: '김갑수',
      deliveryDate: 1,
      star: 4.7,
      reviewCount: 2300,
    ),
    Product(
      name: '서산 생강 1kg',
      price: 11000,
      description: '향이 강한 서산 생강입니다.',
      imageUrl: 'assets/manbok_seosan_ginger.png',
      origin: '충남 서산',
      farmer: '이만복',
      deliveryDate: 1,
      star: 4.3,
      reviewCount: 1458,
    ),
    Product(
      name: '영양 고추 2kg',
      price: 9500,
      description: '알싸한 맛이 일품인 영양 고추입니다.',
      imageUrl: 'assets/sangsik_yeongyang_pepper.png',
      origin: '경북 영양',
      farmer: '이상식',
      deliveryDate: 2,
      star: 4.1,
      reviewCount: 1231,
    ),
    Product(
      name: '성주 참외 3개',
      price: 8500,
      description: '달콤한 성주 참외입니다.',
      imageUrl: 'assets/sungyoung_sungju_Koreanmelon.png',
      origin: '경북 성주',
      farmer: '강성영',
      deliveryDate: 1,
      star: 4.4,
      reviewCount: 578,
    ),
    Product(
      name: '증평 인삼 100g',
      price: 25000,
      description: '고품질 증평 인삼입니다.',
      imageUrl: 'assets/youngpal_Jeungpyeong_ginseng.png',
      origin: '충북 증평',
      farmer: '최영팔',
      deliveryDate: 3,
      star: 4.9,
      reviewCount: 178,
    ),
  ];
}
